"""
PORTION ESTIMATOR MODULE  –  Direct Proportion + Heaping Factor
====================================================================
The camera overlay locks the plate to a FIXED size and distance, so
compartment pixel areas are one-time constants measured from empty_plate.png
at its native 1524×1557 resolution via watershed segmentation.

ALGORITHM:
  1. YOLO detects food items → bounding boxes
  2. OpenCV GrabCut → precise binary food mask per detection
  3. Pixel-overlap → assigns each food to its compartment
  4. fill_ratio = food_pixels / compartment_pixels   (0 … 1)
  5. Heaping Factor Correction: Compensates for Z-axis overflow for solid foods.
  6. food_volume_ml = fill_ratio × compartment_volume_ml × heaping_multiplier
  7. food_grams     = food_volume_ml  × food_density_g_per_ml
"""

import cv2
import numpy as np
import json
import os
import io
from PIL import Image as PILImage, ImageOps
from ultralytics import SAM

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Initialize MobileSAM globally so it only loads into RAM once.
# It will automatically download 'mobile_sam.pt' on the first run.
print("[PortionEstimator] Loading MobileSAM Foundation Model...")
_SAM_PATH = os.path.join(BASE_DIR, "..", "mobile_sam.pt")
sam_model = SAM(_SAM_PATH)

# Set to True when running standalone to visualise GrabCut masks.
# ALWAYS False in production (cv2.waitKey blocks the server).
DEBUG_SHOW_MASKS = False

# ══════════════════════════════════════════════════════════════
# HARDCODED CONSTANTS  (from plate_calibration.json)
# ══════════════════════════════════════════════════════════════

# Standard resolution — every incoming photo is resized to this
STANDARD_W = 1524
STANDARD_H = 1557

# Compartment pixel areas (from precise auto-calibration)
COMPARTMENT_PIXELS = {
    "main_carb": 911005,   # large section         (~43.0 %)
    "side_1":    406813,   # rectangle section     (~19.2 %)
    "side_2":    262181,   # small square section  (~12.4 %)
}

# Centroids (for mapping YOLO bbox → compartment)
COMPARTMENT_CENTROIDS = {
    "main_carb": (449,  777),
    "side_1":    (1144, 1019),
    "side_2":    (1128, 353),
}

# Real volumes measured by filling each compartment with water
COMPARTMENT_VOLUME_ML = {
    "main_carb": 580,   # ml  (large section)
    "side_1":    250,   # ml  (rectangle section)
    "side_2":    165,   # ml  (small square section)
}

# ── Physical plate geometry ──────────────────────────────────
# Coordinate thresholds at standard resolution (calculated from plate center)
COMPARTMENT_X_SPLIT = 761
COMPARTMENT_Y_SPLIT = 778


# ══════════════════════════════════════════════════════════════
# FOOD DENSITY & HEAPING DATABASE
# ══════════════════════════════════════════════════════════════

# FOOD_DENSITY (g / ml) ← bulk density at LEVEL FILL
FOOD_DENSITY = {
    # ── Rice & Starches ──────────────────────────────────────
    "white rice":     1,
    "red rice":       0.85,
    "fried rice":     0.75,
    "roti":           0.55,
    "string hoppers": 0.40,
    "pittu":          0.72,
    "hoppers":        0.38,

    # ── Curries & Protein ────────────────────────────────────
    "chicken":         1.5,
    "fish curry":      0.80,
    "dahl curry":      1.25,
    "Beans curry":     0.65,
    "egg":             0.95,
    "cutlet":          0.60,
    "tempered sprats": 0.50,

    # ── Vegetables & Sides ───────────────────────────────────
    "mallum":                   0.35,
    "mallum - gotukola":        0.35,
    "mallum - mukunuwenna":     0.35,
    "mallum - murunga":         0.35,
    "mallum - kathurumurunga":  0.35,
    "mallum - asamodagam":      0.35,
    "beetroot":                 0.70,
    "Pol sambol":               0.45,
    "Pol sambol - tempered":    0.45,
    "Pol sambol - lime added":  0.75,

    # ── Fruits ───────────────────────────────────────────────
    "avacado":   0.90,
    "pineapple": 0.85,

    # ── Fallback ──────────────
    "_default":  0.75,
}

# HEAPING_FACTOR (Z-Axis Height Compensator)
# Adjusts the volume multiplier for solid foods that pile up over the rim
HEAPING_FACTOR = {
    "chicken": 1.4,        # High stacking, leaves air gaps
    "fish curry": 1.2,     # Moderate stacking
    "dahl curry": 1.0,     # Liquid, settles flat to the rim
    "white rice": 1.1,     # Can be slightly heaped
    "red rice": 1.1,
    "fried rice": 1.1,
    "_default": 1.0        # Default to flat fill
}


# ══════════════════════════════════════════════════════════════
# COMPARTMENT MASKS  (loaded once from .npz)
# ══════════════════════════════════════════════════════════════
_masks = {}   # name → uint8 mask (1524×1557)

def _load_masks():
    """Load pre-computed binary masks (generated by auto_calibrate / save script)."""
    global _masks
    npz_path = os.path.join(BASE_DIR, "compartment_masks.npz")
    if not os.path.exists(npz_path):
        print("[PortionEstimator] WARNING: compartment_masks.npz not found – "
              "run calibration first!")
        return
    data = np.load(npz_path)
    for name in data.files:
        m = data[name]
        # Ensure standard resolution
        if m.shape[0] != STANDARD_H or m.shape[1] != STANDARD_W:
            m = cv2.resize(m, (STANDARD_W, STANDARD_H), interpolation=cv2.INTER_NEAREST)
        _masks[name] = m
    print(f"[PortionEstimator] Loaded masks: {list(_masks.keys())}")
    for name, m in _masks.items():
        px = int(np.count_nonzero(m))
        vol = COMPARTMENT_VOLUME_ML.get(name, "?")
        print(f"  {name}: {px:,} px, volume={vol} ml")

_load_masks()


# ══════════════════════════════════════════════════════════════
# CORE FUNCTIONS
# ══════════════════════════════════════════════════════════════

def standardize_image(cv_img):
    """Resize any incoming image to the fixed overlay resolution."""
    h, w = cv_img.shape[:2]
    if w != STANDARD_W or h != STANDARD_H:
        cv_img = cv2.resize(cv_img, (STANDARD_W, STANDARD_H),
                            interpolation=cv2.INTER_AREA)
    return cv_img


def standardize_incoming_image(image_bytes):
    """
    EXIF Failsafe + Resize — run on every image received from the mobile app.
    """
    # 1. Strip hidden EXIF rotation
    pil_img = PILImage.open(io.BytesIO(image_bytes))
    pil_img = ImageOps.exif_transpose(pil_img)

    # 2. PIL RGB → OpenCV BGR
    cv_img = cv2.cvtColor(np.array(pil_img), cv2.COLOR_RGB2BGR)

    # 3. Force to calibration resolution
    cv_img = cv2.resize(cv_img, (STANDARD_W, STANDARD_H),
                        interpolation=cv2.INTER_AREA)
    return cv_img

def create_food_mask(cv_img, x1, y1, x2, y2):
    """
    Create a precise binary food mask using MobileSAM with YOLO bbox as a spatial prompt.
    Falls back to the raw bbox if SAM fails.
    """
    h, w = cv_img.shape[:2]
    x1, y1 = max(0, x1), max(0, y1)
    x2, y2 = min(w, x2), min(h, y2)
    bw, bh = x2 - x1, y2 - y1

    mask = np.zeros((h, w), dtype=np.uint8)

    if bw < 10 or bh < 10:
        mask[y1:y2, x1:x2] = 255
        return mask

    try:
        # Pass the YOLO bounding box as a spatial prompt to MobileSAM
        results = sam_model.predict(cv_img, bboxes=[[x1, y1, x2, y2]], verbose=False)

        if results and results[0].masks is not None:
            sam_mask = results[0].masks.data[0].cpu().numpy()

            if sam_mask.shape != (h, w):
                sam_mask = cv2.resize(sam_mask, (w, h), interpolation=cv2.INTER_NEAREST)

            mask[sam_mask > 0] = 255
        else:
            mask[y1:y2, x1:x2] = 255

        if DEBUG_SHOW_MASKS:
            preview = mask[y1:y2, x1:x2]
            cv2.imshow("SAM Mask - What the AI sees", preview)
            cv2.waitKey(0)
            cv2.destroyWindow("SAM Mask - What the AI sees")

    except Exception as e:
        print(f"[PortionEstimator] SAM Segmentation error: {e}. Falling back to bbox.")
        mask[y1:y2, x1:x2] = 255

    return mask

def map_food_to_compartment(cx, cy):
    """
    Determine which compartment a food belongs to using bbox centre
    coordinates at the standard 1524×1557 resolution.
    """
    if cx < COMPARTMENT_X_SPLIT:
        return "main_carb"
    elif cy < COMPARTMENT_Y_SPLIT:
        return "side_2"
    else:
        return "side_1"


def _count_food_pixels(food_mask, compartment):
    """
    Count how many food pixels fall inside the given compartment.
    """
    if compartment in _masks:
        overlap = cv2.bitwise_and(food_mask, _masks[compartment])
        return int(cv2.countNonZero(overlap))
    return int(cv2.countNonZero(food_mask))


def estimate_portion(food_name, food_mask, cx, cy):
    """
    Direct-proportion estimation with Heaping Factor correction.
    """
    # 1. Compartment by centre coordinates
    compartment = map_food_to_compartment(cx, cy)

    # 2. Count food pixels inside that compartment
    food_pixels = _count_food_pixels(food_mask, compartment)

    if food_pixels < 50:
        return {
            "food":            food_name,
            "estimated_grams": 0,
            "compartment":     compartment,
            "error":           "Too few food pixels detected in compartment",
        }

    comp_total_px = COMPARTMENT_PIXELS[compartment]
    comp_volume   = COMPARTMENT_VOLUME_ML[compartment]
    density       = FOOD_DENSITY.get(food_name, FOOD_DENSITY["_default"])
    heaping_mult  = HEAPING_FACTOR.get(food_name, HEAPING_FACTOR["_default"])

    # ── Direct proportion with Heaping Fix ─────────────────────────
    fill_ratio     = food_pixels / comp_total_px
    food_volume_ml = fill_ratio * comp_volume * heaping_mult
    food_grams     = food_volume_ml * density

    return {
        "food":               food_name,
        "compartment":        compartment,
        "food_pixels":        food_pixels,
        "compartment_pixels": comp_total_px,
        "fill_ratio":         round(fill_ratio, 4),
        "heaping_factor":     heaping_mult,
        "food_volume_ml":     round(food_volume_ml, 1),
        "density_g_per_ml":   density,
        "estimated_grams":    round(food_grams, 1),
        "confidence":         _confidence(fill_ratio, food_pixels),
    }


def _confidence(fill_ratio, food_pixels):
    """Simple heuristic confidence 0–1."""
    if 0.10 <= fill_ratio <= 0.95:
        fc = 1.0
    elif 0.05 <= fill_ratio < 0.10 or 0.95 < fill_ratio <= 1.0:
        fc = 0.7
    else:
        fc = 0.4

    if food_pixels > 5000:
        pc = 1.0
    elif food_pixels > 1000:
        pc = 0.8
    elif food_pixels > 200:
        pc = 0.6
    else:
        pc = 0.3
    return round(fc * 0.6 + pc * 0.4, 2)


# ══════════════════════════════════════════════════════════════
# HIGH-LEVEL API  (called by predictor.py)
# ══════════════════════════════════════════════════════════════

def estimate_all_portions(cv_img, yolo_boxes):
    """
    Estimate portions for every YOLO detection in one call.
    """
    std_img = standardize_image(cv_img)
    h, w = std_img.shape[:2]
    orig_h, orig_w = cv_img.shape[:2]
    sx, sy = w / orig_w, h / orig_h

    results = []
    for det in yolo_boxes:
        food_name = det["food"]
        ox1, oy1, ox2, oy2 = det["bbox"]

        # Scale bbox to standard resolution
        bx1 = int(ox1 * sx)
        by1 = int(oy1 * sy)
        bx2 = int(ox2 * sx)
        by2 = int(oy2 * sy)

        # Precise food mask via GrabCut
        food_mask = create_food_mask(std_img, bx1, by1, bx2, by2)

        # Bbox centre at standard resolution
        cx = (bx1 + bx2) // 2
        cy = (by1 + by2) // 2

        # Direct-proportion estimation
        est = estimate_portion(food_name, food_mask, cx, cy)
        est["detection_confidence"] = det.get("confidence", 0)
        est["bbox"] = [ox1, oy1, ox2, oy2]
        results.append(est)

    return results


# ══════════════════════════════════════════════════════════════
# STANDALONE TEST
# ══════════════════════════════════════════════════════════════
if __name__ == "__main__":
    DEBUG_SHOW_MASKS = True
    print("\n=== Portion Estimator – Direct Proportion Test ===\n")
    print("(GrabCut mask windows will pop up – press any key to continue each one)\n")

    if not _masks:
        print("No masks loaded. Run calibration first!")
    else:
        main_mask = _masks.get("main_carb")
        if main_mask is not None:
            kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (20, 20))
            partial = cv2.erode(main_mask, kernel)

            cv2.namedWindow("GrabCut Mask - What the AI sees", cv2.WINDOW_NORMAL)
            cv2.resizeWindow("GrabCut Mask - What the AI sees", 600, 600)
            cv2.imshow("GrabCut Mask - What the AI sees", partial)
            print(">> Showing mask for: white rice (main_carb) – press any key to continue")
            cv2.waitKey(0)
            cv2.destroyWindow("GrabCut Mask - What the AI sees")

            result = estimate_portion("white rice", partial,
                                      cx=COMPARTMENT_CENTROIDS["main_carb"][0],
                                      cy=COMPARTMENT_CENTROIDS["main_carb"][1])
            print(json.dumps(result, indent=2))

        cv2.destroyAllWindows()
