/**
 * Expo Config Plugin: Fix C++ STL linking for Android native modules.
 *
 * NDK 27 + CMake 3.22 sometimes omits libc++_shared.so from the link line
 * when ANDROID_STL=c++_shared. This causes undefined symbol errors for
 * operator new/delete, std::string, __cxa_*, etc.
 *
 * Fix: Use React Native's documented custom CMakeLists.txt approach.
 * We create a custom CMakeLists.txt that calls link_libraries(c++_shared)
 * before including ReactNative-application.cmake, ensuring all targets
 * (including autolinked native modules) get linked against libc++_shared.
 */
const { withDangerousMod, withAppBuildGradle } = require("expo/config-plugins");
const fs = require("fs");
const path = require("path");

// Custom CMakeLists.txt that adds link_libraries(c++_shared) before RN include
const CUSTOM_CMAKELISTS = `# Custom CMakeLists.txt - Fix C++ STL linking (NDK 27 + CMake 3.22 workaround)
# Generated by withAndroidCxxFix Expo config plugin
cmake_minimum_required(VERSION 3.13)
project(appmodules)

# Fix: Ensure libc++_shared is linked for ALL shared library targets.
# This must come BEFORE ReactNative-application.cmake which creates
# autolinked targets (react_codegen_*) that need C++ standard library symbols.
link_libraries(c++_shared)

include(\${REACT_ANDROID_DIR}/cmake-utils/ReactNative-application.cmake)
`;

// OnLoad.cpp copied from react-native/ReactAndroid/cmake-utils/default-app-setup/OnLoad.cpp
const ONLOAD_CPP = `// OnLoad.cpp - Default React Native JNI initialization
// Copied from react-native default-app-setup for custom CMakeLists.txt support
#include <DefaultComponentsRegistry.h>
#include <DefaultTurboModuleManagerDelegate.h>
#include <FBReactNativeSpec.h>
#include <autolinking.h>
#include <fbjni/fbjni.h>
#include <react/renderer/componentregistry/ComponentDescriptorProviderRegistry.h>

#ifdef REACT_NATIVE_APP_CODEGEN_HEADER
#include REACT_NATIVE_APP_CODEGEN_HEADER
#endif
#ifdef REACT_NATIVE_APP_COMPONENT_DESCRIPTORS_HEADER
#include REACT_NATIVE_APP_COMPONENT_DESCRIPTORS_HEADER
#endif

namespace facebook::react {

void registerComponents(
    std::shared_ptr<const ComponentDescriptorProviderRegistry> registry) {
#ifdef REACT_NATIVE_APP_COMPONENT_REGISTRATION
  REACT_NATIVE_APP_COMPONENT_REGISTRATION(registry);
#endif
  autolinking_registerProviders(registry);
}

std::shared_ptr<TurboModule> cxxModuleProvider(
    const std::string& name,
    const std::shared_ptr<CallInvoker>& jsInvoker) {
  return autolinking_cxxModuleProvider(name, jsInvoker);
  return nullptr;
}

std::shared_ptr<TurboModule> javaModuleProvider(
    const std::string& name,
    const JavaTurboModule::InitParams& params) {
#ifdef REACT_NATIVE_APP_MODULE_PROVIDER
  auto module = REACT_NATIVE_APP_MODULE_PROVIDER(name, params);
  if (module != nullptr) {
    return module;
  }
#endif
  if (auto module = FBReactNativeSpec_ModuleProvider(name, params)) {
    return module;
  }
  if (auto module = autolinking_ModuleProvider(name, params)) {
    return module;
  }
  return nullptr;
}

} // namespace facebook::react

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* vm, void*) {
  return facebook::jni::initialize(vm, [] {
    facebook::react::DefaultTurboModuleManagerDelegate::cxxModuleProvider =
        &facebook::react::cxxModuleProvider;
    facebook::react::DefaultTurboModuleManagerDelegate::javaModuleProvider =
        &facebook::react::javaModuleProvider;
    facebook::react::DefaultComponentsRegistry::
        registerComponentDescriptorsFromEntryPoint =
            &facebook::react::registerComponents;
  });
}
`;

function withAndroidCxxFix(config) {
  // Step 1: Create custom JNI files (CMakeLists.txt + OnLoad.cpp)
  config = withDangerousMod(config, [
    "android",
    async (config) => {
      const jniDir = path.join(
        config.modRequest.platformProjectRoot,
        "app",
        "src",
        "main",
        "jni",
      );
      fs.mkdirSync(jniDir, { recursive: true });
      fs.writeFileSync(path.join(jniDir, "CMakeLists.txt"), CUSTOM_CMAKELISTS);
      fs.writeFileSync(path.join(jniDir, "OnLoad.cpp"), ONLOAD_CPP);
      console.log(
        "[withAndroidCxxFix] Created custom CMakeLists.txt + OnLoad.cpp in android/app/src/main/jni/",
      );
      return config;
    },
  ]);

  // Step 2: Add externalNativeBuild to app/build.gradle
  config = withAppBuildGradle(config, (config) => {
    if (config.modResults.language === "groovy") {
      const contents = config.modResults.contents;
      const externalBuildBlock = `
    // Fix: Use custom CMakeLists.txt with libc++_shared linkage fix
    externalNativeBuild {
        cmake {
            path "src/main/jni/CMakeLists.txt"
        }
    }`;

      // Insert inside the android {} block, after namespace line
      if (!contents.includes('path "src/main/jni/CMakeLists.txt"')) {
        config.modResults.contents = contents.replace(
          /namespace\s+'[^']+'/,
          (match) => match + "\n" + externalBuildBlock,
        );
      }
    }
    return config;
  });

  return config;
}

module.exports = withAndroidCxxFix;
